"""A fake `uv`, a fake `curl` and a real tarball, for the per-server build.

`handover_executor_fixtures.FakeRun` records children and scripts answers.
The per-server build needs more than an answer: `uv venv` must leave a
`bin/python`, `uv pip compile` must leave a lock, and `curl` must leave a
file whose BYTES the build then hashes. A fake that only recorded the argv
would make "a lock whose hash does not match" untestable, because nothing
would have a hash.

So this fake DOES what each command does, minimally, and the test controls
what it produces. Nothing here runs `uv`, `curl` or `runuser`.
"""

from __future__ import annotations

import hashlib
import io
import tarfile
from collections.abc import Callable
from dataclasses import dataclass, field
from pathlib import Path

from handover.executor.host import Command
from handover.executor.host import Result as RunResult
from handover.mcpserver import ServerFile, parse_server

KAGI_YAML = """
name: kagi
identity: "The fleet's Kagi API key."
install:
  source: pypi
  package: kagimcp
  version: 1.0.2
  lock: {lock}
  python: "3.12"
run:
  entrypoint: kagimcp
  env:
    KAGI_API_KEY: secret:kagi_api_key
tools:
  - name: kagi_search_fetch
    description: Search the web.
"""

GITHUB_YAML = """
name: github-code
identity: "Fine-grained PAT for every repository except the platform three."
install:
  source: github-release
  repo: github/github-mcp-server
  version: 1.12.0
  asset: github-mcp-server_Linux_x86_64.tar.gz
  sha256: "{sha256}"
run:
  entrypoint: github-mcp-server
  args: [stdio]
tools:
  - name: get_file_contents
    description: Read one file.
"""

#: Contract 01b §3.3: an `agent-mcp` server declares NO ref. The
#: `mcp-servers` component tag is the version of every server the
#: repository ships.
VIKUNJA_YAML = """
name: vikunja-finance
identity: "The Vikunja bot bot-finance."
install:
  source: agent-mcp
run:
  entrypoint: vikunja-mcp
  env:
    VIKUNJA_TOKEN: secret:vikunja_token_finance
tools:
  - name: get_ticket
    description: Read one ticket.
"""

#: The committed closure (contract 01b §3.4), as `uv pip compile
#: --generate-hashes` writes one. Root installs FROM this file and resolves
#: nothing, so what it says is what lands.
LOCK_HASH_LINE = "--hash=sha256:11ce3c58a18fbb06d4f3b4d7ffdc8f1d2e0e5a7c9b4a3d20516e7f8c9a0b1c2d"

LOCK_TEXT = f"""# This file was autogenerated by uv via the following command:
#    uv pip compile --generate-hashes --python-platform linux requirements.in
kagimcp==1.0.2 \\
    {LOCK_HASH_LINE}
"""

#: Where contract 01b §8.1 puts it, beside the declaration.
KAGI_LOCK_PATH = "mcp/kagi/install.lock"


def kagi_server(lock: str = KAGI_LOCK_PATH) -> ServerFile:
    return parse_server(KAGI_YAML.format(lock=lock).encode("utf-8"), "kagi")


def github_server(sha256: str) -> ServerFile:
    return parse_server(GITHUB_YAML.format(sha256=sha256).encode("utf-8"), "github-code")


def vikunja_server() -> ServerFile:
    return parse_server(VIKUNJA_YAML.encode("utf-8"), "vikunja-finance")


def release_tarball(
    entrypoint: str = "github-mcp-server", body: bytes = b"#!/x\nexit 0\n"
) -> bytes:
    """A real `.tar.gz` holding one executable at its top level, which is
    the shape github-mcp-server's Linux asset has."""
    buffer = io.BytesIO()
    with tarfile.open(fileobj=buffer, mode="w:gz") as tar:
        info = tarfile.TarInfo(entrypoint)
        info.size = len(body)
        info.mode = 0o755
        tar.addfile(info, io.BytesIO(body))

    return buffer.getvalue()


def hostile_tarball(make: Callable[[tarfile.TarFile], None]) -> bytes:
    """One archive a test builds member by member, for §4.2's unpack rules."""
    buffer = io.BytesIO()
    with tarfile.open(fileobj=buffer, mode="w:gz") as tar:
        make(tar)

    return buffer.getvalue()


def sha256_of(raw: bytes) -> str:
    return hashlib.sha256(raw).hexdigest()


@dataclass
class McpFake:
    """`uv`, `curl`, `install`, `chown` and `chmod`, as a recorded runner.

    Each one does the smallest real thing: `uv venv` makes `bin/python`,
    `uv pip compile` writes `lock_text`, `uv pip install` writes the
    entrypoint script, and `curl` writes `asset_bytes`. A test makes exactly
    one of them fail with `fails`.
    """

    asset_bytes: bytes = b""
    #: An argv word to the exit code the child answers with.
    fails: dict[str, int] = field(default_factory=dict[str, int])
    #: `uv pip install` writes this instead of a plain console script, so a
    #: test can prove the non-relocatable shebang is caught.
    shebang: str = "#!/bin/sh\n"
    #: The console script `uv pip install` leaves in the venv. A test that
    #: builds a second server sets it, because one fake serves one build.
    entrypoint: str = "kagimcp"
    #: Where `uv sync --frozen` was told to build, read off the child's env.
    venv_env: str = ""
    #: The minors the host itself provides (`uv python find` answers for
    #: them). 3.12 is the host's; `ha-mcp` wants 3.13, which it does not have.
    pythons_on_host: tuple[str, ...] = ("3.12",)
    #: `UV_PYTHON_INSTALL_DIR`, read off a child's env.
    python_root: Path | None = None
    #: A path OUTSIDE the tree that the install leaves in a `.pth`, the way
    #: an editable `uv sync` does. Empty means the install is self-contained,
    #: which is what `--no-editable` buys.
    pth_outside: str = ""
    seen: list[Command] = field(default_factory=list[Command])

    def __call__(self, command: Command) -> RunResult:
        self.seen.append(command)
        argv = list(command.argv)
        for name, value in command.env:
            if name == "UV_PROJECT_ENVIRONMENT":
                self.venv_env = value
            if name == "UV_PYTHON_INSTALL_DIR":
                self.python_root = Path(value)
        for word, code in self.fails.items():
            if any(word in one for one in argv):
                return RunResult(code, "", f"{word} failed\n")

        for handle in (
            self._python_find,
            self._python_install,
            self._venv,
            self._install_pkg,
            self._sync,
            self._curl,
            self._mkdir,
        ):
            answered = handle(argv)
            if answered is not None:
                return answered

        return RunResult(0, "", "")

    def argv_lines(self) -> list[str]:
        return [" ".join(one.argv) for one in self.seen]

    def ran(self, word: str) -> bool:
        return any(word in line for line in self.argv_lines())

    def identity_of(self, word: str) -> Command | None:
        for one in self.seen:
            if any(word in part for part in one.argv):
                return one

        return None

    # -- one behaviour per command --------------------------------------

    def _python_find(self, argv: list[str]) -> RunResult | None:
        """`uv python find <minor>`: found when the host has it
        (`pythons_on_host`) or an earlier install put it in the shared
        directory."""
        if argv[1:3] != ["python", "find"]:
            return None

        minor = argv[-1]
        installed = self.python_root is not None and any(self.python_root.glob(f"cpython-{minor}*"))
        if minor in self.pythons_on_host or installed:
            return RunResult(0, f"/usr/bin/python{minor}\n", "")

        return RunResult(2, "", f"error: No interpreter found for Python {minor}\n")

    def _python_install(self, argv: list[str]) -> RunResult | None:
        """`uv python install --no-bin <minor>`: one directory under the
        shared root, the way a real install leaves one."""
        if argv[1:3] != ["python", "install"]:
            return None

        assert self.python_root is not None, "install without UV_PYTHON_INSTALL_DIR"
        (self.python_root / f"cpython-{argv[-1]}.0-linux-x86_64-gnu" / "bin").mkdir(
            parents=True, exist_ok=True, mode=0o750
        )

        return RunResult(0, "", "")

    def _venv(self, argv: list[str]) -> RunResult | None:
        if "venv" not in argv:
            return None

        new = Path(argv[-1])
        (new / "bin").mkdir(parents=True, exist_ok=True)
        (new / "bin" / "python").write_text("#!/x\n", encoding="utf-8")

        return RunResult(0, "", "")

    def _install_pkg(self, argv: list[str]) -> RunResult | None:
        if "pip" not in argv or "install" not in argv:
            return None

        python = Path(argv[argv.index("--python") + 1])

        return self._write_script(python.parent.parent)

    def _write_script(self, venv: Path) -> RunResult:
        script = venv / "bin" / self.entrypoint
        script.parent.mkdir(parents=True, exist_ok=True)
        script.write_text(f"{self.shebang}exit 0\n", encoding="utf-8")
        script.chmod(0o755)
        # What a real install leaves beside the script: the site-packages
        # `check_tree` walks. Empty is self-contained.
        site = venv / "lib" / "python3.12" / "site-packages"
        site.mkdir(parents=True, exist_ok=True)
        if self.pth_outside:
            (site / "_editable_impl_agent_mcp.pth").write_text(
                f"{self.pth_outside}\n", encoding="utf-8"
            )

        return RunResult(0, "", "")

    def _sync(self, argv: list[str]) -> RunResult | None:
        """`uv sync --frozen --no-editable`, which is how a `source:
        agent-mcp` server is installed: from that tree's own committed
        `uv.lock`, built into the tree."""
        if "sync" not in argv:
            return None

        return self._write_script(Path(self.venv_env or "."))

    def _curl(self, argv: list[str]) -> RunResult | None:
        if not argv[0].endswith("curl"):
            return None

        Path(argv[argv.index("--output") + 1]).write_bytes(self.asset_bytes)

        return RunResult(0, "", "")

    def _mkdir(self, argv: list[str]) -> RunResult | None:
        """`install -d`. Root makes the staged directory for the server's
        own user; the test has no second user, so it just makes it."""
        if not argv[0].endswith("/install") or "-d" not in argv:
            return None

        Path(argv[-1]).mkdir(parents=True, exist_ok=True)

        return RunResult(0, "", "")
