"""The one test that builds a binary tree with the real `cargo`.

Every other `kind: binary` test fakes the build, and a fake cannot show
what the real tool writes. An editable venv tree reached a host through
four gates that each faked `uv` (`test_handover_ced_uv_guard.py`). So this
module runs the build argv of the fixture manifest, with the `cargo` this
machine has, and asks the built tree three questions:

1. Does each program sit at `<staged tree>/bin/<name>`, when the build
   learns the staged tree from `CARGO_INSTALL_ROOT` alone?
2. Does `--no-track` keep cargo's own records out of the tree? They name
   the directory that the build ran in.
3. With the tree renamed and the fetched work tree GONE, does a program
   still run?

The workspace is written into `tmp_path`: one crate, two programs and no
dependency, so the build reads no index and needs no network. The test
sets `CARGO_NET_OFFLINE` to hold that, and a `CARGO_HOME` of its own so the
build writes nothing into this machine's.

Skipped where the machine has no `cargo`. Marked slow: it compiles.
"""

from __future__ import annotations

import os
import shutil
import stat
import subprocess
from pathlib import Path
from typing import Final

import pytest
from handover.executor.install import BINARY_ENV_NAME
from handover.manifest import ComponentManifest, parse_manifest
from handover_bin_fixtures import BINARY_MANIFEST, BINARY_NAME

pytestmark = pytest.mark.slow

BUILD_TIMEOUT_S: Final = 600.0

VERIFY_NAME: Final = f"{BINARY_NAME}-verify"

#: What the verify program prints. The test runs it out of the moved tree.
VERIFY_SAYS: Final = "ok"

#: Cargo's records of what it installed, and from which directory.
TRACK_FILES: Final = (".crates.toml", ".crates2.json")

#: The flag of the fixture manifest that keeps those records out.
NO_TRACK: Final = "--no-track"

WORKSPACE_TOML: Final = '[workspace]\nresolver = "2"\nmembers = ["crates/*"]\n'

CRATE_TOML: Final = f"""\
[package]
name = "{BINARY_NAME}"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "{BINARY_NAME}"
path = "src/main.rs"

[[bin]]
name = "{VERIFY_NAME}"
path = "src/verify.rs"
"""

#: A lock file for one crate with no dependency, so `--locked` has nothing
#: to resolve and nothing to fetch.
LOCK: Final = f"""\
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3

[[package]]
name = "{BINARY_NAME}"
version = "0.1.0"
"""

MAIN_RS: Final = 'fn main() {\n    println!("the component");\n}\n'
VERIFY_RS: Final = f'fn main() {{\n    println!("{VERIFY_SAYS}");\n}}\n'


def _cargo() -> str:
    """The `cargo` THIS machine has. The manifest names `/usr/local/bin/
    cargo`, which is the host's. What the test proves is what the argv
    AFTER `argv[0]` does, so the binary may be wherever it is here."""
    found = shutil.which("cargo")
    if found is None:
        pytest.skip("cargo is not on this machine")

    return found


def _manifest() -> ComponentManifest:
    return parse_manifest(BINARY_MANIFEST.read_text(encoding="utf-8"), "fixture/component.yaml")


def _workspace(root: Path) -> Path:
    """A fetched work tree: the repository root, with the Cargo workspace
    under `rust/` and the crate that the fixture manifest's build names."""
    crate = root / "rust" / "crates" / BINARY_NAME
    (crate / "src").mkdir(parents=True)
    (root / "rust" / "Cargo.toml").write_text(WORKSPACE_TOML, encoding="utf-8")
    (root / "rust" / "Cargo.lock").write_text(LOCK, encoding="utf-8")
    (crate / "Cargo.toml").write_text(CRATE_TOML, encoding="utf-8")
    (crate / "src" / "main.rs").write_text(MAIN_RS, encoding="utf-8")
    (crate / "src" / "verify.rs").write_text(VERIFY_RS, encoding="utf-8")

    return root


def _build(tmp_path: Path, argv: tuple[str, ...], source: Path, new: Path) -> None:
    """One build argv, run the way the executor runs it: in the fetched
    tree, with the staged tree named by `BINARY_ENV_NAME` and nothing else
    of this process's cargo configuration."""
    env = {
        "PATH": os.environ["PATH"],
        "HOME": os.environ.get("HOME", str(tmp_path)),
        "LANG": "C.UTF-8",
        "CARGO_HOME": str(tmp_path / "cargo-home"),
        "CARGO_NET_OFFLINE": "true",
        BINARY_ENV_NAME: str(new),
    }
    for name in ("RUSTUP_HOME", "RUSTUP_TOOLCHAIN"):
        if name in os.environ:
            env[name] = os.environ[name]

    done = subprocess.run(
        [_cargo(), *argv[1:]],
        cwd=str(source),
        env=env,
        capture_output=True,
        text=True,
        timeout=BUILD_TIMEOUT_S,
        check=False,
    )

    assert done.returncode == 0, done.stderr


def _entries(tree: Path) -> set[str]:
    return {path.relative_to(tree).as_posix() for path in tree.rglob("*")}


@pytest.fixture
def built(tmp_path: Path) -> tuple[Path, Path]:
    """The fixture manifest's own build, done. Answers the fetched work
    tree and the staged tree."""
    source = _workspace(tmp_path / "work" / BINARY_NAME)
    new = tmp_path / "components" / f"{BINARY_NAME}.new"
    new.parent.mkdir(parents=True)
    for argv in _manifest().build:
        _build(tmp_path, argv, source, new)

    return source, new


def test_the_fixture_build_keeps_cargos_records_out() -> None:
    """The argv this module runs is the manifest's own, so the flag is
    checked where it is written."""
    (argv,) = _manifest().build

    assert argv[1] == "install"
    assert "--locked" in argv
    assert NO_TRACK in argv
    assert "--root" not in argv


def test_each_program_lands_under_bin_of_the_staged_tree(built: tuple[Path, Path]) -> None:
    """Question 1. The build argv names no output directory. The programs
    are at `<staged tree>/bin/<name>`, the layout a venv has."""
    _, new = built

    for name in (BINARY_NAME, VERIFY_NAME):
        facts = os.lstat(new / "bin" / name)
        assert stat.S_ISREG(facts.st_mode), name
        assert facts.st_mode & stat.S_IXUSR, name


def test_the_staged_tree_holds_the_programs_and_nothing_else(built: tuple[Path, Path]) -> None:
    """Question 2. With `--no-track` the tree is `bin/` and two programs."""
    _, new = built

    assert _entries(new) == {"bin", f"bin/{BINARY_NAME}", f"bin/{VERIFY_NAME}"}


def test_without_no_track_cargo_records_the_work_tree(tmp_path: Path) -> None:
    """Why the flag is there. Without it cargo writes two records into the
    tree, and they name the directory that the build ran in."""
    source = _workspace(tmp_path / "work" / BINARY_NAME)
    new = tmp_path / "components" / f"{BINARY_NAME}.new"
    new.parent.mkdir(parents=True)
    (argv,) = _manifest().build
    _build(tmp_path, tuple(word for word in argv if word != NO_TRACK), source, new)

    for name in TRACK_FILES:
        assert str(source) in (new / name).read_text(encoding="utf-8"), name


def test_a_program_runs_after_the_rename_with_the_work_tree_gone(
    tmp_path: Path, built: tuple[Path, Path]
) -> None:
    """Question 3. Step 9 renames `<install.to>.new` to `<install.to>`, and
    the fetched work tree is not part of what runs."""
    source, new = built
    live = new.with_name(BINARY_NAME)
    os.rename(new, live)
    shutil.rmtree(source)

    done = subprocess.run(
        [str(live / "bin" / VERIFY_NAME)],
        cwd=str(tmp_path),
        env={"PATH": "/usr/bin:/bin"},
        capture_output=True,
        text=True,
        timeout=60.0,
        check=False,
    )

    assert done.returncode == 0, done.stderr
    assert done.stdout.strip() == VERIFY_SAYS
